name: Node.js CI - Compute metrics

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - run: npm ci

    - run: npm run build --if-present

    - run: npm start

    - name: Archive the main output file
      uses: actions/upload-artifact@v3
      with:
        name: all.csv
        path: stats/all.csv